# Generated by Django 4.2.1 on 2023-08-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0003_findjob_delete_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='findjob',
            name='club_type',
            field=models.CharField(choices=[('jobs', 'Jobs'), ('clubs', 'Clubs')], default='jobs', max_length=20),
        ),
        migrations.AddField(
            model_name='findjob',
            name='type',
            field=models.CharField(choices=[('school', 'School'), ('college', 'College'), ('institute', 'Institute')], default='school', max_length=20),
        ),
    ]
